CMS/Controllers/ProductController.cs
using Samples.NServiceBus.CMS.Domain;
using Samples.NServiceBus.CMS.EventPublication;
using Samples.NServiceBus.Repositories;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Samples.NServiceBus.CMS
{
    public class ProductController : Controller
    {
        private readonly IRepository<Product> productRepository;
        private readonly IProductEventPublication productEventPublication;

        public ProductController(IRepository<Product> productRepository, IProductEventPublication productEventPublication)
        {
            this.productRepository = productRepository;
            this.productEventPublication = productEventPublication;
        }

        public ActionResult Index()
        {
            return View(productRepository.GetAll());
        }

        public ActionResult Details(Guid id)
        {
            var product = productRepository.GetById(id);
            return View(product);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                productRepository.Insert(product);
                productRepository.SaveChanges();

                productEventPublication.ProductWasAdded(product);

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Edit(Guid id)
        {
            var product = productRepository.GetById(id);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Guid id, Product product)
        {
            if (ModelState.IsValid)
            {
                var dbProduct = productRepository.GetById(id);
                dbProduct.Name = product.Name;
                dbProduct.Price = product.Price;
                dbProduct.Description = product.Description;
                dbProduct.Purchased = product.Purchased;
                productRepository.SaveChanges();

                productEventPublication.ProductWasUpdated(product);

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Delete(Guid id)
        {
            var product = productRepository.GetById(id);
            return View(product);
        }

        [HttpPost]
        public ActionResult Delete(Guid id, Product product)
        {
            try
            {
                var dbProduct = productRepository.GetById(id);
                productRepository.Delete(dbProduct);
                productRepository.SaveChanges();

                productEventPublication.ProductWasRemoved(product);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ToWebshop()
        {
            HttpContext.Response.Redirect(ConfigurationManager.AppSettings["Sample.WebshopUrl"]);
            return new EmptyResult();
        }
    }
}

CMS/Views/Product/Create.cshtml
@model Samples.NServiceBus.CMS.Domain.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create product</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.Partial("_Form", Model)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CMS/Views/Product/Delete.cshtml
@model Samples.NServiceBus.CMS.Domain.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Are you sure you want to delete this product?</h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

CMS/Views/Product/Edit.cshtml
@model Samples.NServiceBus.CMS.Domain.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit product</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.Partial("_Form", Model)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</div>

CMS/Views/Product/Index.cshtml
@model IEnumerable<Samples.NServiceBus.CMS.Domain.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Available products</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>

@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Purchased)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Purchased)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
}
else
{
    <i>There are no products yet. Please add some, so you can see that it all works :)</i>
}

CMS/Views/Product/_Form.cshtml
@model Samples.NServiceBus.CMS.Domain.Product

@{
    Layout = null;
}

@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">
    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Purchased, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.CheckBoxFor(model => model.Purchased, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Purchased, "", new { @class = "text-danger" })
    </div>
</div>

CMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CMS</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CMS", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Product")</li>
                    <li>@Html.ActionLink("Webshop", "ToWebshop", "Product")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Christiaan Verwijs</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
</body>
</html>